### ISSUE TITLE
Don't link issues within backquotes

### ISSUE THREAD

**Issue by rarkins** [sindresorhus/linkify-issues#4]
Do you think it's possible to somehow skip issues that are located within backquotes, e.g. not match/linkify `#123` or `Issues #123 and #456`? Linkifying those would result in a pretty ugly output or the user, but I wonder if *accurately* identifying those would require stateful parsing of markdown to achieve.

**Comment by sindresorhus** [comment]
We could support `#123` by just excluding matches preceded by a backtick, but the second one will be nearly impossible without doing full Markdown parsing.

**Comment by rarkins** [comment]
Would you achieve that by making it a negative match within https://github.com/sindresorhus/issue-regex though? I'm not sure escaped issues necessarily goes against *that* repository's goals.

**Comment by sindresorhus** [comment]
We can do it in `issue-regex`, but it will require backtracking which is only available in Node.js 10, see also: https://github.com/sindresorhus/issue-regex/issues/3

**Comment by fregante** [comment]
I think this module should be run on clean strings only. The string you're mentioning is a markdown string, so you should probably be using a markdown parser instead of this module (or at least parse it yourself before passing it here.)

Otherwise, why should it support backticks and not the HTML string `"<code>#124</code>"`? What about TeX? Or other markup?

**Comment by rarkins** [comment]
This can be closed, as Renovate Bot no longer uses this library. FYI it was used against release notes as part of its efforts to identify github backlinks and escape them, so avoid "backlink spam".
